---
version: '2'
services:
  kafka-1:
    image: confluentinc/cp-server:latest
    network_mode: host
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT:  ${IP_ADDRESS_1}:22181,${IP_ADDRESS_1}:32181,${IP_ADDRESS_2}:22181,${IP_ADDRESS_3}:22181,${IP_ADDRESS_3}:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${IP_ADDRESS_1}:19092
      KAFKA_CONFLUENT_METADATA_SERVER_ADVERTISED_LISTENERS: http://${IP_ADDRESS_1}:8093
      KAFKA_CONFLUENT_METADATA_SERVER_LISTENERS: http://0.0.0.0:8093
      KAFKA_CONFLUENT_METADATA_SERVER_METHOD: BEARER
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: ${IP_ADDRESS_1}:19092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: ${IP_ADDRESS_1}:22181,${IP_ADDRESS_1}:32181,${IP_ADDRESS_2}:22181,${IP_ADDRESS_3}:22181,${IP_ADDRESS_3}:32181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      
      
  kafka-2:
    image: confluentinc/cp-server:latest
    network_mode: host
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT:  ${IP_ADDRESS_1}:22181,${IP_ADDRESS_1}:32181,${IP_ADDRESS_2}:22181,${IP_ADDRESS_3}:22181,${IP_ADDRESS_3}:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${IP_ADDRESS_1}:29092
      KAFKA_CONFLUENT_METADATA_SERVER_ADVERTISED_LISTENERS: http://${IP_ADDRESS_1}:8091
      KAFKA_CONFLUENT_METADATA_SERVER_LISTENERS: http://0.0.0.0:8091
      KAFKA_CONFLUENT_METADATA_SERVER_METHOD: BEARER
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9102
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: ${IP_ADDRESS_1}:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: ${IP_ADDRESS_1}:22181,${IP_ADDRESS_1}:32181,${IP_ADDRESS_2}:22181,${IP_ADDRESS_3}:22181,${IP_ADDRESS_3}:32181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      
  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    container_name: control-center
    network_mode: host

    environment:
      # CUB CLASSPATH
      CUB_CLASSPATH: '/etc/confluent/docker/docker-utils.jar:/usr/share/java/confluent-control-center/*:/usr/share/java/rest-utils/*:/usr/share/java/confluent-common/*'
      # CUB_CLASSPATH: '/etc/confluent/docker/docker-utils.jar:/usr/share/java/confluent-control-center/*'

      # general settings
      CONTROL_CENTER_BOOTSTRAP_SERVERS: ${IP_ADDRESS_1}:19092,${IP_ADDRESS_1}:29092,${IP_ADDRESS_2}:19092,${IP_ADDRESS_2}:29092,${IP_ADDRESS_3}:19092,${IP_ADDRESS_3}:29092,${IP_ADDRESS_4}:19092,${IP_ADDRESS_4}:29092
      

      # Amount of heap to use for internal caches. Increase for better throughput
      CONTROL_CENTER_STREAMS_CACHE_MAX_BYTES_BUFFERING: 100000000
      CONTROL_CENTER_STREAMS_CONSUMER_REQUEST_TIMEOUT_MS: "960032"
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 1

      
      # HTTP to Control Center UI 
      CONTROL_CENTER_REST_LISTENERS: http://0.0.0.0:9021
      PORT: 9021

