---
version: '2'
services:
  kafka-1:
    image: confluentinc/cp-server:latest
    network_mode: host
    volumes:
     - ${LOCAL_CERTS_LOCATION}:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT:   ${HOST_NAME_1}:22182
      KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: 'true'
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
      KAFKA_SSL_CLIENT_AUTH: requested
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_1}.keystore.jks
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_1}.truststore.jks
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_ADVERTISED_LISTENERS: SSL://${HOST_NAME_1}:19093
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: ${HOST_NAME_1}:19093
      CONFLUENT_METRICS_REPORTER_SECURITY_PROTOCOL: SSL
      CONFLUENT_METRICS_REPORTER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_1}.truststore.jks
      CONFLUENT_METRICS_REPORTER_SSL_TRUSTSTORE_PASSWORD: confluent
      CONFLUENT_METRICS_REPORTER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_1}.keystore.jks
      CONFLUENT_METRICS_REPORTER_SSL_KEYSTORE_PASSWORD: confluent
      CONFLUENT_METRICS_REPORTER_SSL_KEY_PASSWORD: confluent
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_BROKER_RACK: 'walnut'
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.${HOST_NAME_1}.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ${HOST_NAME_1}_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: ${HOST_NAME_1}_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.${HOST_NAME_1}.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ${HOST_NAME_1}_truststore_creds
      KAFKA_CONFLUENT_METADATA_SERVER_ADVERTISED_LISTENERS: https://${HOST_NAME_1}:8094
      KAFKA_CONFLUENT_METADATA_SERVER_LISTENERS: https://0.0.0.0:8094
      KAFKA_CONFLUENT_METADATA_SERVER_METHOD: BEARER
      KAFKA_CONFLUENT_METADATA_SERVER_SSL_KEYSTORE_LOCATION: kafka.${HOST_NAME_1}.keystore.jks
      KAFKA_CONFLUENT_METADATA_SERVER_SSL_KEYSTORE_PASSWORD: ${HOST_NAME_1}_keystore_creds
      KAFKA_CONFLUENT_METADATA_SERVER_SSL_KEY_PASSWORD: ${HOST_NAME_1}_sslkey_creds
      KAFKA_CONFLUENT_METADATA_SERVER_SSL_TRUSTSTORE_LOCATION: kafka.${HOST_NAME_1}.truststore.jks
      KAFKA_CONFLUENT_METADATA_SERVER_SSL_TRUSTSTORE_PASSWORD: ${HOST_NAME_1}_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      
  kafka-2:
    image: confluentinc/cp-server:latest
    network_mode: host
    volumes:
     - ${LOCAL_CERTS_LOCATION}:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT:   ${HOST_NAME_1}:32182
      KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: 'true'
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
      KAFKA_SSL_CLIENT_AUTH: requested
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_1}.keystore.jks
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_1}.truststore.jks
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_ADVERTISED_LISTENERS: SSL://${HOST_NAME_1}:29093
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: ${HOST_NAME_1}:29093
      CONFLUENT_METRICS_REPORTER_SECURITY_PROTOCOL: SSL
      CONFLUENT_METRICS_REPORTER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_1}.truststore.jks
      CONFLUENT_METRICS_REPORTER_SSL_TRUSTSTORE_PASSWORD: confluent
      CONFLUENT_METRICS_REPORTER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_1}.keystore.jks
      CONFLUENT_METRICS_REPORTER_SSL_KEYSTORE_PASSWORD: confluent
      CONFLUENT_METRICS_REPORTER_SSL_KEY_PASSWORD: confluent
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9102
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_BROKER_RACK: 'walnut'
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.${HOST_NAME_1}.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ${HOST_NAME_1}_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: ${HOST_NAME_1}_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.${HOST_NAME_1}.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ${HOST_NAME_1}_truststore_creds
      KAFKA_CONFLUENT_METADATA_SERVER_ADVERTISED_LISTENERS: https://${HOST_NAME_1}:8094
      KAFKA_CONFLUENT_METADATA_SERVER_LISTENERS: https://0.0.0.0:8095
      KAFKA_CONFLUENT_METADATA_SERVER_METHOD: BEARER
      KAFKA_CONFLUENT_METADATA_SERVER_SSL_KEYSTORE_LOCATION: kafka.${HOST_NAME_1}.keystore.jks
      KAFKA_CONFLUENT_METADATA_SERVER_SSL_KEYSTORE_PASSWORD: ${HOST_NAME_1}_keystore_creds
      KAFKA_CONFLUENT_METADATA_SERVER_SSL_KEY_PASSWORD: ${HOST_NAME_1}_sslkey_creds
      KAFKA_CONFLUENT_METADATA_SERVER_SSL_TRUSTSTORE_LOCATION: kafka.${HOST_NAME_1}.truststore.jks
      KAFKA_CONFLUENT_METADATA_SERVER_SSL_TRUSTSTORE_PASSWORD: ${HOST_NAME_1}_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "      
      
  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    container_name: control-center
    network_mode: host
    volumes:
     - ${LOCAL_CERTS_LOCATION}:/etc/kafka/secrets
    environment:
      # CUB CLASSPATH
      CUB_CLASSPATH: '/etc/confluent/docker/docker-utils.jar:/usr/share/java/confluent-control-center/*:/usr/share/java/rest-utils/*:/usr/share/java/confluent-common/*'
      # CUB_CLASSPATH: '/etc/confluent/docker/docker-utils.jar:/usr/share/java/confluent-control-center/*'

      # general settings
      CONTROL_CENTER_BOOTSTRAP_SERVERS: ${HOST_NAME_1}:19092,${HOST_NAME_1}:29092,${HOST_NAME_2}:19092,${HOST_NAME_2}:29092,${HOST_NAME_3}:19092,${HOST_NAME_3}:29092,${HOST_NAME_4}:19092,${HOST_NAME_4}:29092
      

      # Amount of heap to use for internal caches. Increase for better throughput
      CONTROL_CENTER_STREAMS_CACHE_MAX_BYTES_BUFFERING: 100000000
      CONTROL_CENTER_STREAMS_CONSUMER_REQUEST_TIMEOUT_MS: "960032"
      CONTROL_CENTER_REPLICATION_FACTOR: 6
      
      # HTTP to Control Center UI 
      # Amount of heap to use for internal caches. Increase for better throughput

      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 1

      CONTROL_CENTER_STREAMS_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_1}.truststore.jks
      CONTROL_CENTER_STREAMS_SSL_TRUSTSTORE_PASSWORD: confluent
      CONTROL_CENTER_STREAMS_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_1}.keystore.jks
      CONTROL_CENTER_STREAMS_SSL_KEYSTORE_PASSWORD: confluent
      CONTROL_CENTER_STREAMS_SSL_KEY_PASSWORD: confluent
      CONTROL_CENTER_STREAMS_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"

      # HTTP and HTTPS to Control Center UI 
      CONTROL_CENTER_REST_LISTENERS: https://0.0.0.0:9022
      CONTROL_CENTER_REST_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_1}.truststore.jks
      CONTROL_CENTER_REST_SSL_TRUSTSTORE_PASSWORD: confluent
      CONTROL_CENTER_REST_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_1}.keystore.jks
      CONTROL_CENTER_REST_SSL_KEYSTORE_PASSWORD: confluent
      CONTROL_CENTER_REST_SSL_KEY_PASSWORD: confluent
      CONTROL_CENTER_SSL_CIPHER_SUITES: "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
      PORT: 9022



