---
version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    volumes:
     - ${LOCAL_CERTS_LOCATION}:/etc/kafka/secrets    
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SECURE_CLIENT_PORT: 22182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: ${HOST_NAME_1}:22888:23888;${HOST_NAME_1}:32888:33888;${HOST_NAME_2}:22888:23888;${HOST_NAME_3}:22888:23888;${HOST_NAME_3}:32888:33888
      ZOOKEEPER_SERVER_CNXN_FACTORY: org.apache.zookeeper.server.NettyServerCnxnFactory
      ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_2}.keystore.jks
      ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent
      ZOOKEEPER_SSL_KEYSTORE_TYPE: PKCS12
      ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_2}.truststore.jks
      ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent
      ZOOKEEPER_SSL_TRUSTSTORE_TYPE: JKS
      ZOOKEEPER_SSL_QUORUM: 'true'
      ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_2}.keystore.jks
      ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent
      ZOOKEEPER_SSL_KEYSTORE_TYPE: PKCS12
      ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_2}.truststore.jks
      ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent
      ZOOKEEPER_SSL_TRUSTSTORE_TYPE: JKS      
      ZOOKEEPER_SSL_QUORUM_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_2}.keystore.jks
      ZOOKEEPER_SSL_QUORUM_KEYSTORE_PASSWORD: confluent
      ZOOKEEPER_SSL_QUORUM_KEYSTORE_TYPE: PKCS12
      ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.${HOST_NAME_2}.truststore.jks
      ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_PASSWORD: confluent
      ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_TYPE: JKS
    network_mode: host